// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mdld_cpp
IntegerVector mdld_cpp(CharacterVector s1, CharacterVector s2, int block_limit, int max_distance);
RcppExport SEXP _TNRS_mdld_cpp(SEXP s1SEXP, SEXP s2SEXP, SEXP block_limitSEXP, SEXP max_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< int >::type block_limit(block_limitSEXP);
    Rcpp::traits::input_parameter< int >::type max_distance(max_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(mdld_cpp(s1, s2, block_limit, max_distance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TNRS_mdld_cpp", (DL_FUNC) &_TNRS_mdld_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_TNRS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
