# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mdld_cpp <- function(s1, s2, block_limit, max_distance) {
    .Call('_TNRS_mdld_cpp', PACKAGE = 'TNRS', s1, s2, block_limit, max_distance)
}

